import * as styles from './styles.scss';

interface StaticComponentTemplateData {

}

export default (render: Function, data: StaticComponentTemplateData) => {
    return render`
        <style>${styles.toString()}</style>
        <div class="static__component">
            <h1>Peppa 1</h1>
            <h2>Peppa 2</h2>
            <h3>Peppa 3</h3>
            <h4>Peppa 4</h4>
            <h5>Peppa 5</h5>
            <h6>Peppa 6</h6>
            <img src="../resources/img/pig.png">
            <p>Lorem ipsum dolor amet <strong>yOLO</strong> succulents chartreuse 3 wolf moon PBR&B synth prism health goth beard quinoa direct trade chia mixtape. Letterpress iPhone glossier poke. 8-bit butcher enamel pin freegan lumbersexual. Stumptown readymade kitsch godard four dollar toast. Photo booth sartorial cliche chillwave cray meggings banh mi thundercats fingerstache pug trust fund. Portland neutra cornhole, master cleanse venmo keytar skateboard air plant vegan. Neutra tbh drinking vinegar tattooed. Church-key organic etsy vinyl, jianbing knausgaard flannel coloring book. Organic iceland subway tile ugh 3 wolf moon mixtape. Heirloom messenger bag enamel pin taiyaki echo park wayfarers food truck pinterest four loko organic. Hella franzen ennui slow-carb vice actually. Subway tile organic tattooed roof party, hoodie umami knausgaard iceland chillwave franzen meh shaman hexagon seitan helvetica. Raw denim edison bulb blue bottle, microdosing green juice hashtag cornhole pitchfork. Kickstarter bushwick edison bulb gluten-free drinking vinegar brooklyn heirloom kogi direct trade pinterest irony ugh. Food truck sustainable poke subway tile, chartreuse seitan migas pickled la croix. Pour-over microdosing iceland wayfarers church-key sustainable skateboard, cliche deep v. Drinking vinegar chicharrones bespoke distillery hashtag direct trade pok pok messenger bag jean shorts four dollar toast raclette affogato af.</p>
            <p>Lorem ipsum dolor amet <strong>yOLO</strong> succulents chartreuse 3 wolf moon PBR&B synth prism health goth beard quinoa direct trade chia mixtape. Letterpress iPhone glossier poke. 8-bit butcher enamel pin freegan lumbersexual. Stumptown readymade kitsch godard four dollar toast. Photo booth sartorial cliche chillwave cray meggings banh mi thundercats fingerstache pug trust fund. Portland neutra cornhole, master cleanse venmo keytar skateboard air plant vegan. Neutra tbh drinking vinegar tattooed. Church-key organic etsy vinyl, jianbing knausgaard flannel coloring book. Organic iceland subway tile ugh 3 wolf moon mixtape. Heirloom messenger bag enamel pin taiyaki echo park wayfarers food truck pinterest four loko organic. Hella franzen ennui slow-carb vice actually. Subway tile organic tattooed roof party, hoodie umami knausgaard iceland chillwave franzen meh shaman hexagon seitan helvetica. Raw denim edison bulb blue bottle, microdosing green juice hashtag cornhole pitchfork. Kickstarter bushwick edison bulb gluten-free drinking vinegar brooklyn heirloom kogi direct trade pinterest irony ugh. Food truck sustainable poke subway tile, chartreuse seitan migas pickled la croix. Pour-over microdosing iceland wayfarers church-key sustainable skateboard, cliche deep v. Drinking vinegar chicharrones bespoke distillery hashtag direct trade pok pok messenger bag jean shorts four dollar toast raclette affogato af.</p>
            <p>Lorem ipsum dolor amet <strong>yOLO</strong> succulents chartreuse 3 wolf moon PBR&B synth prism health goth beard quinoa direct trade chia mixtape. Letterpress iPhone glossier poke. 8-bit butcher enamel pin freegan lumbersexual. Stumptown readymade kitsch godard four dollar toast. Photo booth sartorial cliche chillwave cray meggings banh mi thundercats fingerstache pug trust fund. Portland neutra cornhole, master cleanse venmo keytar skateboard air plant vegan. Neutra tbh drinking vinegar tattooed. Church-key organic etsy vinyl, jianbing knausgaard flannel coloring book. Organic iceland subway tile ugh 3 wolf moon mixtape. Heirloom messenger bag enamel pin taiyaki echo park wayfarers food truck pinterest four loko organic. Hella franzen ennui slow-carb vice actually. Subway tile organic tattooed roof party, hoodie umami knausgaard iceland chillwave franzen meh shaman hexagon seitan helvetica. Raw denim edison bulb blue bottle, microdosing green juice hashtag cornhole pitchfork. Kickstarter bushwick edison bulb gluten-free drinking vinegar brooklyn heirloom kogi direct trade pinterest irony ugh. Food truck sustainable poke subway tile, chartreuse seitan migas pickled la croix. Pour-over microdosing iceland wayfarers church-key sustainable skateboard, cliche deep v. Drinking vinegar chicharrones bespoke distillery hashtag direct trade pok pok messenger bag jean shorts four dollar toast raclette affogato af.</p>
        </div>
    `;
}
